[world]
kind = "WorldContract"
class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
original_class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x2a9b2d8dc43c75312bf14df3f83fcd68b2d4fd6945d91acccb6e9a669e56fad"
transaction_hash = "0x1b9af98fcb458b482703699952c91d2067f0b2293632874586c5dd397e10173"
block_number = 3
seed = "skeleton_smash"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x64a81532dec0aae2c41da0d4556b3727ab13231b77a4defdc3f480ac1dae8eb"
class_hash = "0x62d777fab8290c4f14107ff35cba181bb37c926dd074a1778c353d103584e42"
original_class_hash = "0x62d777fab8290c4f14107ff35cba181bb37c926dd074a1778c353d103584e42"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/skeleton_smash-actions-7ca74759.json"
reads = []
writes = [
    "skeleton_smash-Player",
    "skeleton_smash-Position",
    "skeleton_smash-Room",
    "skeleton_smash-RoomList",
    "skeleton_smash-Run",
]
init_calldata = []
tag = "skeleton_smash-actions"
systems = [
    "initialize",
    "spawn",
    "move",
    "first_move",
]
manifest_name = "skeleton_smash-actions-7ca74759"

[[models]]
kind = "DojoModel"
class_hash = "0x26ce9155befef69bf54a9195fc854f0d11d196c9e3c1fde64438cb4a17c1e9"
original_class_hash = "0x26ce9155befef69bf54a9195fc854f0d11d196c9e3c1fde64438cb4a17c1e9"
abi = "manifests/dev/deployment/abis/models/skeleton_smash-Movement-192a23ba.json"
tag = "skeleton_smash-Movement"
qualified_path = "skeleton_smash::models::player::movement"
manifest_name = "skeleton_smash-Movement-192a23ba"

[[models.members]]
name = "run_id"
type = "u32"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x29672b150d63723fb9be7e1214447bbce4eb0ba120f364ee4dc60e391843896"
original_class_hash = "0x29672b150d63723fb9be7e1214447bbce4eb0ba120f364ee4dc60e391843896"
abi = "manifests/dev/deployment/abis/models/skeleton_smash-Player-2b480015.json"
tag = "skeleton_smash-Player"
qualified_path = "skeleton_smash::models::player::player"
manifest_name = "skeleton_smash-Player-2b480015"

[[models.members]]
name = "contract_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "run_id"
type = "u32"
key = false

[[models.members]]
name = "run_history"
type = "Array<u32>"
key = false

[[models.members]]
name = "in_run"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4de6c0a28038b1b7725d441e4f80ecea189b3f467d0b4b9bee0a84aa8df9152"
original_class_hash = "0x4de6c0a28038b1b7725d441e4f80ecea189b3f467d0b4b9bee0a84aa8df9152"
abi = "manifests/dev/deployment/abis/models/skeleton_smash-Position-53f482b3.json"
tag = "skeleton_smash-Position"
qualified_path = "skeleton_smash::models::player::position"
manifest_name = "skeleton_smash-Position-53f482b3"

[[models.members]]
name = "run_id"
type = "u32"
key = true

[[models.members]]
name = "pos"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x36873160f677497c6e7571712ec2ab6ea4c602fff8936d5ec7df902f6a1a910"
original_class_hash = "0x36873160f677497c6e7571712ec2ab6ea4c602fff8936d5ec7df902f6a1a910"
abi = "manifests/dev/deployment/abis/models/skeleton_smash-Room-164aae80.json"
tag = "skeleton_smash-Room"
qualified_path = "skeleton_smash::models::map::room"
manifest_name = "skeleton_smash-Room-164aae80"

[[models.members]]
name = "room_id"
type = "u32"
key = true

[[models.members]]
name = "map"
type = "felt252"
key = false

[[models.members]]
name = "player_positions"
type = "felt252"
key = false

[[models.members]]
name = "level"
type = "u32"
key = false

[[models.members]]
name = "run_ids"
type = "Array<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x762243a7081c8f6e2a3a12f65f988fd21633b6be99a63e85b07e6eb06622af6"
original_class_hash = "0x762243a7081c8f6e2a3a12f65f988fd21633b6be99a63e85b07e6eb06622af6"
abi = "manifests/dev/deployment/abis/models/skeleton_smash-RoomList-2d4ebfa4.json"
tag = "skeleton_smash-RoomList"
qualified_path = "skeleton_smash::models::map::room_list"
manifest_name = "skeleton_smash-RoomList-2d4ebfa4"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "room_max_id_for_level"
type = "Array<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x695817357de69aa5831f65f62c8e3876f7325ec9747fe0bf44865e50ab72424"
original_class_hash = "0x695817357de69aa5831f65f62c8e3876f7325ec9747fe0bf44865e50ab72424"
abi = "manifests/dev/deployment/abis/models/skeleton_smash-Run-4d03c68b.json"
tag = "skeleton_smash-Run"
qualified_path = "skeleton_smash::models::player::run"
manifest_name = "skeleton_smash-Run-4d03c68b"

[[models.members]]
name = "run_id"
type = "u32"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = false

[[models.members]]
name = "room_id"
type = "u32"
key = false

[[models.members]]
name = "level"
type = "u32"
key = false

[[models.members]]
name = "move_count"
type = "u32"
key = false

[[models.members]]
name = "is_dead"
type = "bool"
key = false
