kind = "DojoModel"
class_hash = "0x4836bba7ffc627401f58a8a51a1b94fd5807c2ef56ec2744670e347112e3dec"
original_class_hash = "0x4836bba7ffc627401f58a8a51a1b94fd5807c2ef56ec2744670e347112e3dec"
abi = "manifests/dev/base/abis/models/skeleton_smash-Room-164aae80.json"
tag = "skeleton_smash-Room"
qualified_path = "skeleton_smash::models::map::room"
manifest_name = "skeleton_smash-Room-164aae80"

[[members]]
name = "room_id"
type = "u32"
key = true

[[members]]
name = "map"
type = "felt252"
key = false

[[members]]
name = "level"
type = "u32"
key = false

[[members]]
name = "player_ids"
type = "Array<ContractAddress>"
key = false
