kind = "DojoModel"
class_hash = "0x3024497a9eebb754ac7841682adf045f62bb25be5bfcc5a223abcf52b353069"
original_class_hash = "0x3024497a9eebb754ac7841682adf045f62bb25be5bfcc5a223abcf52b353069"
abi = "manifests/dev/base/abis/models/skeleton_smash-Moves-40fd8284.json"
tag = "skeleton_smash-Moves"
qualified_path = "skeleton_smash::models::setup::moves"
manifest_name = "skeleton_smash-Moves-40fd8284"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "remaining"
type = "u8"
key = false

[[members]]
name = "last_direction"
type = "Direction"
key = false

[[members]]
name = "can_move"
type = "bool"
key = false
