kind = "DojoModel"
class_hash = "0x42b45acc93f0d911099b35053761a1ae5c943a450b489b195f5d256dfb1cd01"
original_class_hash = "0x42b45acc93f0d911099b35053761a1ae5c943a450b489b195f5d256dfb1cd01"
abi = "manifests/dev/base/abis/models/skeleton_smash-Position-53f482b3.json"
tag = "skeleton_smash-Position"
qualified_path = "skeleton_smash::models::player::position"
manifest_name = "skeleton_smash-Position-53f482b3"

[[members]]
name = "run_id"
type = "u32"
key = true

[[members]]
name = "vec"
type = "Vec2"
key = false
