kind = "DojoModel"
class_hash = "0x64ae51976b82c8c42e0987e9dfcb7864211f0da30fb87e112e068d518304786"
original_class_hash = "0x64ae51976b82c8c42e0987e9dfcb7864211f0da30fb87e112e068d518304786"
abi = "manifests/dev/base/abis/models/skeleton_smash-DirectionsAvailable-1a861750.json"
tag = "skeleton_smash-DirectionsAvailable"
qualified_path = "skeleton_smash::models::setup::directions_available"
manifest_name = "skeleton_smash-DirectionsAvailable-1a861750"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "directions"
type = "Array<Direction>"
key = false
