kind = "DojoModel"
class_hash = "0x5b5f91000cc366b2cad2b14efeddbde91709a066b1716aea28ae05dea219030"
original_class_hash = "0x5b5f91000cc366b2cad2b14efeddbde91709a066b1716aea28ae05dea219030"
abi = "manifests/dev/base/abis/models/skeleton_smash-Position-53f482b3.json"
tag = "skeleton_smash-Position"
qualified_path = "skeleton_smash::models::setup::position"
manifest_name = "skeleton_smash-Position-53f482b3"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "vec"
type = "Vec2"
key = false
