kind = "DojoModel"
class_hash = "0x56f34d78226df321e3844b6f9839459d28760252210ad9079ee1514f13ce8fb"
original_class_hash = "0x56f34d78226df321e3844b6f9839459d28760252210ad9079ee1514f13ce8fb"
abi = "manifests/dev/base/abis/models/skeleton_smash-DirectionsAvailable-1a861750.json"
tag = "skeleton_smash-DirectionsAvailable"
qualified_path = "skeleton_smash::models::directions_available"
manifest_name = "skeleton_smash-DirectionsAvailable-1a861750"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "directions"
type = "Array<Direction>"
key = false
