kind = "DojoModel"
class_hash = "0x762243a7081c8f6e2a3a12f65f988fd21633b6be99a63e85b07e6eb06622af6"
original_class_hash = "0x762243a7081c8f6e2a3a12f65f988fd21633b6be99a63e85b07e6eb06622af6"
abi = "manifests/dev/base/abis/models/skeleton_smash-RoomList-2d4ebfa4.json"
tag = "skeleton_smash-RoomList"
qualified_path = "skeleton_smash::models::map::room_list"
manifest_name = "skeleton_smash-RoomList-2d4ebfa4"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "room_max_id_for_level"
type = "Array<u32>"
key = false
