kind = "DojoModel"
class_hash = "0x7d000915ee55cc46f10cac904371b319143be0916e06968e8c765698e41d29f"
original_class_hash = "0x7d000915ee55cc46f10cac904371b319143be0916e06968e8c765698e41d29f"
abi = "manifests/dev/base/abis/models/skeleton_smash-Position-53f482b3.json"
tag = "skeleton_smash-Position"
qualified_path = "skeleton_smash::models::position"
manifest_name = "skeleton_smash-Position-53f482b3"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "vec"
type = "Vec2"
key = false
