[world]
name = "skeleton smash"
description = "A fully onchain telegram game"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "skeleton_smash"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "skeleton_smash"

[env]
rpc_url = "https://api.cartridge.gg/x/skelton-smash/katana"
# Default account for katana with seed = 0
account_address = "0x4a92c703ced69b13e696e68086516cdadbcf7d9b0c22899bf0e280280f0210a"
private_key = "0xb053744d9d6b1d8f5dbfe7502052c2716849fe5ef2609a62d52d25940a4455"
world_address = "0x2a9b2d8dc43c75312bf14df3f83fcd68b2d4fd6945d91acccb6e9a669e56fad"
