[package]
cairo-version = "=2.7.0"
name = "skeleton_smash"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply"


[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.12" }
origami_map = { git = "https://github.com/dojoengine/origami" }

[[target.dojo]]

[profile.slot]