kind = "DojoModel"
class_hash = "0x36873160f677497c6e7571712ec2ab6ea4c602fff8936d5ec7df902f6a1a910"
original_class_hash = "0x36873160f677497c6e7571712ec2ab6ea4c602fff8936d5ec7df902f6a1a910"
abi = "manifests/slot/base/abis/models/skeleton_smash-Room-164aae80.json"
tag = "skeleton_smash-Room"
qualified_path = "skeleton_smash::models::map::room"
manifest_name = "skeleton_smash-Room-164aae80"

[[members]]
name = "room_id"
type = "u32"
key = true

[[members]]
name = "map"
type = "felt252"
key = false

[[members]]
name = "player_positions"
type = "felt252"
key = false

[[members]]
name = "level"
type = "u32"
key = false

[[members]]
name = "run_ids"
type = "Array<u32>"
key = false
