kind = "DojoModel"
class_hash = "0x4de6c0a28038b1b7725d441e4f80ecea189b3f467d0b4b9bee0a84aa8df9152"
original_class_hash = "0x4de6c0a28038b1b7725d441e4f80ecea189b3f467d0b4b9bee0a84aa8df9152"
abi = "manifests/slot/base/abis/models/skeleton_smash-Position-53f482b3.json"
tag = "skeleton_smash-Position"
qualified_path = "skeleton_smash::models::player::position"
manifest_name = "skeleton_smash-Position-53f482b3"

[[members]]
name = "run_id"
type = "u32"
key = true

[[members]]
name = "pos"
type = "u8"
key = false
