kind = "DojoContract"
class_hash = "0x57868708f619581d02e1536f715b5a9df323122492f69453fe99c843069ebed"
original_class_hash = "0x57868708f619581d02e1536f715b5a9df323122492f69453fe99c843069ebed"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/skeleton_smash-actions-7ca74759.json"
reads = []
writes = []
init_calldata = []
tag = "skeleton_smash-actions"
systems = [
    "initialize",
    "spawn",
    "move",
    "first_move",
    "seppuku",
]
manifest_name = "skeleton_smash-actions-7ca74759"
