kind = "DojoContract"
class_hash = "0x3895159d18ca7c70ecb07fd19fdafcbbd7c0fd482047924403f09cd96f7cf11"
original_class_hash = "0x3895159d18ca7c70ecb07fd19fdafcbbd7c0fd482047924403f09cd96f7cf11"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/skeleton_smash-actions-7ca74759.json"
reads = []
writes = []
init_calldata = []
tag = "skeleton_smash-actions"
systems = [
    "initialize",
    "spawn",
    "move",
    "first_move",
]
manifest_name = "skeleton_smash-actions-7ca74759"
