kind = "DojoContract"
class_hash = "0x5121ef0b681df7dd3b23bfa057c22649dbe47eac860de47aa3e1414001e3216"
original_class_hash = "0x5121ef0b681df7dd3b23bfa057c22649dbe47eac860de47aa3e1414001e3216"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/skeleton_smash-actions-7ca74759.json"
reads = []
writes = []
init_calldata = []
tag = "skeleton_smash-actions"
systems = [
    "initialize",
    "spawn",
    "move",
    "first_move",
]
manifest_name = "skeleton_smash-actions-7ca74759"
