kind = "DojoContract"
class_hash = "0x639a3f09b7bcf6dadbad52a95f77624a2aebaa2906f51c786664387a90287b1"
original_class_hash = "0x639a3f09b7bcf6dadbad52a95f77624a2aebaa2906f51c786664387a90287b1"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/skeleton_smash-actions-7ca74759.json"
reads = []
writes = []
init_calldata = []
tag = "skeleton_smash-actions"
systems = [
    "initialize",
    "spawn",
    "move_player",
]
manifest_name = "skeleton_smash-actions-7ca74759"
