kind = "DojoContract"
class_hash = "0x31f85ce78134ea7deaf51311f02f396e70906191d645e449e3b65d51696a1e7"
original_class_hash = "0x31f85ce78134ea7deaf51311f02f396e70906191d645e449e3b65d51696a1e7"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/skeleton_smash-actions-7ca74759.json"
reads = []
writes = []
init_calldata = []
tag = "skeleton_smash-actions"
systems = [
    "initialize",
    "spawn",
    "move_player",
    "first_move",
]
manifest_name = "skeleton_smash-actions-7ca74759"
