kind = "DojoContract"
class_hash = "0x617972d2c42d32b1e359eee1155f52b185b86ce94c2f2cce3dc562924f5591e"
original_class_hash = "0x617972d2c42d32b1e359eee1155f52b185b86ce94c2f2cce3dc562924f5591e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/skeleton_smash-actions-7ca74759.json"
reads = []
writes = []
init_calldata = []
tag = "skeleton_smash-actions"
systems = ["spawn"]
manifest_name = "skeleton_smash-actions-7ca74759"
