kind = "DojoContract"
class_hash = "0x1a8b2934c549ed4efa586303cfe365ba0b0541d3e7d045d8c6de40010251178"
original_class_hash = "0x1a8b2934c549ed4efa586303cfe365ba0b0541d3e7d045d8c6de40010251178"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/skeleton_smash-actions-7ca74759.json"
reads = []
writes = []
init_calldata = []
tag = "skeleton_smash-actions"
systems = [
    "initialize",
    "spawn",
    "move",
    "first_move",
]
manifest_name = "skeleton_smash-actions-7ca74759"
