kind = "DojoContract"
class_hash = "0x3430c13e128548557688b891ece3a207fa226866f2bd15123da940230727747"
original_class_hash = "0x3430c13e128548557688b891ece3a207fa226866f2bd15123da940230727747"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/skeleton_smash-actions-7ca74759.json"
reads = []
writes = []
init_calldata = []
tag = "skeleton_smash-actions"
systems = [
    "initialize",
    "spawn",
    "move",
    "first_move",
]
manifest_name = "skeleton_smash-actions-7ca74759"
